/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lpmYViqlg0N
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { CardTitle, CardDescription, CardHeader, CardContent, Card, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function MyCard() {
  return (
    <Card className="mx-auto max-w-screen-sm">
      <CardHeader className="space-y-2 text-center">
        <CardTitle className="text-3xl font-bold">Store</CardTitle>
        <CardDescription>Check out our latest products and offers</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <Card>
              <CardContent className="p-4">
                <h3 className="text-lg font-semibold">Product 1</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Description of Product 1</p>
                <Button className="w-full mt-4" variant="outline">
                  View Details
                </Button>
              </CardContent>
            </Card>
          </div>
          <div>
            <Card>
              <CardContent className="p-4">
                <h3 className="text-lg font-semibold">Product 2</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Description of Product 2</p>
                <Button className="w-full mt-4" variant="outline">
                  View Details
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </CardContent>
      <CardFooter className="space-y-2 text-center">
        <p className="text-gray-500 dark:text-gray-400">
          Explore more products in our store
          <Link className="underline" href="#">
            Go to Store
          </Link>
        </p>
      </CardFooter>
    </Card>
  )
}
